import { Species } from "@snorkeling/shared";
import { CreatureKind } from "@/svg/MarineCreature";

/** A collectible species plus the display data the Collection/Species screens need. */
export interface SpeciesEntry extends Species {
  creature: CreatureKind;
  gradient: [string, string];
}

/**
 * Seed catalog. In a later phase this comes from the backend (06-backend.md);
 * for now it lives on-device. `foundAt` maps to the Puerto Rico dive sites.
 */
export const SPECIES: SpeciesEntry[] = [
  {
    id: "green-turtle",
    commonName: "Green Sea Turtle",
    scientificName: "Chelonia mydas",
    category: "turtle",
    rarity: "uncommon",
    conservationStatus: "Endangered",
    depthMinFt: 3,
    depthMaxFt: 25,
    spotDifficulty: 2,
    funFact:
      "They can hold their breath for up to 5 hours underwater by slowing their heart rate to one beat every few minutes.",
    foundAt: ["Icacos", "Vieques", "Palomino"],
    creature: "turtle",
    gradient: ["#1fc8a8", "#0a9e8e"],
  },
  {
    id: "hawksbill-turtle",
    commonName: "Hawksbill Turtle",
    scientificName: "Eretmochelys imbricata",
    category: "turtle",
    rarity: "rare",
    conservationStatus: "Critically Endangered",
    depthMinFt: 5,
    depthMaxFt: 65,
    spotDifficulty: 3,
    funFact: "Their overlapping shell scutes and pointed beak let them reach sponges other turtles can't.",
    foundAt: ["Vieques"],
    creature: "turtle",
    gradient: ["#2fb89a", "#0a6e7e"],
  },
  {
    id: "queen-angelfish",
    commonName: "Queen Angelfish",
    scientificName: "Holacanthus ciliaris",
    category: "reef",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 3,
    depthMaxFt: 70,
    spotDifficulty: 1,
    funFact: "The dark blue crown-like spot on its forehead is what earned it the name 'queen'.",
    foundAt: ["Icacos", "Palomino"],
    creature: "fish",
    gradient: ["#ffb648", "#ff7a3d"],
  },
  {
    id: "eagle-ray",
    commonName: "Spotted Eagle Ray",
    scientificName: "Aetobatus narinari",
    category: "ray",
    rarity: "uncommon",
    conservationStatus: "Endangered",
    depthMinFt: 10,
    depthMaxFt: 130,
    spotDifficulty: 2,
    funFact: "They leap clear out of the water — some think to escape predators, others to shed parasites.",
    foundAt: ["Icacos", "Vieques"],
    creature: "ray",
    gradient: ["#5b8def", "#3a5fd0"],
  },
  {
    id: "brain-coral",
    commonName: "Brain Coral",
    scientificName: "Diploria labyrinthiformis",
    category: "reef",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 5,
    depthMaxFt: 100,
    spotDifficulty: 1,
    funFact: "A single boulder can be centuries old — the maze-like grooves grow only a few millimeters a year.",
    foundAt: ["Icacos", "Palomino"],
    creature: "coral",
    gradient: ["#ff6fae", "#e0218a"],
  },
  {
    id: "nurse-shark",
    commonName: "Nurse Shark",
    scientificName: "Ginglymostoma cirratum",
    category: "shark",
    rarity: "uncommon",
    conservationStatus: "Vulnerable",
    depthMinFt: 3,
    depthMaxFt: 40,
    spotDifficulty: 2,
    funFact: "Gentle bottom-dwellers, they rest in groups under ledges by day and hunt at night.",
    foundAt: ["Palomino"],
    creature: "shark",
    gradient: ["#7f95a1", "#3f6076"],
  },
  {
    id: "caribbean-reef-shark",
    commonName: "Caribbean Reef Shark",
    scientificName: "Carcharhinus perezi",
    category: "shark",
    rarity: "rare",
    conservationStatus: "Endangered",
    depthMinFt: 15,
    depthMaxFt: 100,
    spotDifficulty: 3,
    funFact: "One of the most common large reef sharks in the Caribbean — and a key sign of a healthy reef.",
    foundAt: ["Vieques"],
    creature: "shark",
    gradient: ["#4a6b7d", "#243b47"],
  },
  {
    id: "common-octopus",
    commonName: "Common Octopus",
    scientificName: "Octopus vulgaris",
    category: "other",
    rarity: "uncommon",
    conservationStatus: "Least Concern",
    depthMinFt: 5,
    depthMaxFt: 90,
    spotDifficulty: 3,
    funFact: "They can change color and texture in under a second to vanish against coral and rock.",
    foundAt: ["Icacos", "Palomino"],
    creature: "octopus",
    gradient: ["#c66fd6", "#7b2ea8"],
  },
  {
    id: "moon-jelly",
    commonName: "Moon Jelly",
    scientificName: "Aurelia aurita",
    category: "other",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 0,
    depthMaxFt: 30,
    spotDifficulty: 1,
    funFact: "Their sting is too weak to hurt you — the four rings you see are actually their stomach.",
    foundAt: ["Icacos"],
    creature: "jelly",
    gradient: ["#7fd0e6", "#3a8fd0"],
  },
  {
    id: "longsnout-seahorse",
    commonName: "Longsnout Seahorse",
    scientificName: "Hippocampus reidi",
    category: "other",
    rarity: "rare",
    conservationStatus: "Near Threatened",
    depthMinFt: 5,
    depthMaxFt: 55,
    spotDifficulty: 3,
    funFact: "It's the male who carries and gives birth to the young, from a pouch on his belly.",
    foundAt: ["Vieques"],
    creature: "seahorse",
    gradient: ["#f4b62e", "#d98a1e"],
  },
  {
    id: "stoplight-parrotfish",
    commonName: "Stoplight Parrotfish",
    scientificName: "Sparisoma viride",
    category: "reef",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 3,
    depthMaxFt: 80,
    spotDifficulty: 1,
    funFact: "They munch coral and excrete fine white sand — one fish can make ~100 kg of beach a year.",
    foundAt: ["Icacos", "Palomino", "Vieques"],
    creature: "fish",
    gradient: ["#2fb87a", "#0a8f5c"],
  },
  {
    id: "blue-tang",
    commonName: "Blue Tang",
    scientificName: "Acanthurus coeruleus",
    category: "reef",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 3,
    depthMaxFt: 65,
    spotDifficulty: 1,
    funFact: "Juveniles are bright yellow and only turn deep blue as they grow up.",
    foundAt: ["Icacos", "Palomino"],
    creature: "fish",
    gradient: ["#2f9bd8", "#1b5fb0"],
  },
  {
    id: "french-angelfish",
    commonName: "French Angelfish",
    scientificName: "Pomacanthus paru",
    category: "reef",
    rarity: "uncommon",
    conservationStatus: "Least Concern",
    depthMinFt: 5,
    depthMaxFt: 100,
    spotDifficulty: 2,
    funFact: "They pair for life and patrol their reef territory together, side by side.",
    foundAt: ["Palomino"],
    creature: "fish",
    gradient: ["#4a4f5c", "#22252e"],
  },
  {
    id: "great-barracuda",
    commonName: "Great Barracuda",
    scientificName: "Sphyraena barracuda",
    category: "other",
    rarity: "uncommon",
    conservationStatus: "Least Concern",
    depthMinFt: 3,
    depthMaxFt: 100,
    spotDifficulty: 2,
    funFact: "They hang almost motionless, then strike at up to 35 mph — one of the fastest fish on the reef.",
    foundAt: ["Vieques", "Icacos"],
    creature: "fish",
    gradient: ["#9bb0bd", "#5c7382"],
  },
  {
    id: "southern-stingray",
    commonName: "Southern Stingray",
    scientificName: "Hypanus americanus",
    category: "ray",
    rarity: "common",
    conservationStatus: "Near Threatened",
    depthMinFt: 3,
    depthMaxFt: 55,
    spotDifficulty: 1,
    funFact: "They flap sand over their bodies to hide, leaving only their eyes peeking out.",
    foundAt: ["Icacos", "Palomino"],
    creature: "ray",
    gradient: ["#a99a86", "#6e5f4a"],
  },
  {
    id: "cushion-star",
    commonName: "Cushion Sea Star",
    scientificName: "Oreaster reticulatus",
    category: "other",
    rarity: "common",
    conservationStatus: "Least Concern",
    depthMinFt: 3,
    depthMaxFt: 35,
    spotDifficulty: 1,
    funFact: "Lose an arm to a predator and it simply regrows — slowly, over many months.",
    foundAt: ["Icacos"],
    creature: "star",
    gradient: ["#ff8a3d", "#e0552f"],
  },
  {
    id: "trumpetfish",
    commonName: "Trumpetfish",
    scientificName: "Aulostomus maculatus",
    category: "reef",
    rarity: "uncommon",
    conservationStatus: "Least Concern",
    depthMinFt: 5,
    depthMaxFt: 80,
    spotDifficulty: 2,
    funFact: "They hover vertically among sea rods, pretending to be a swaying branch to ambush prey.",
    foundAt: ["Palomino", "Vieques"],
    creature: "fish",
    gradient: ["#c9b04a", "#8f7a1e"],
  },
  {
    id: "spotted-drum",
    commonName: "Spotted Drum",
    scientificName: "Equetus punctatus",
    category: "reef",
    rarity: "rare",
    conservationStatus: "Least Concern",
    depthMinFt: 10,
    depthMaxFt: 100,
    spotDifficulty: 3,
    funFact: "Its long ribbon-like dorsal fin waves constantly as it circles under dark ledges.",
    foundAt: ["Vieques"],
    creature: "fish",
    gradient: ["#5c6270", "#2a2e38"],
  },
];

export const TOTAL_SPECIES = SPECIES.length;

export function speciesById(id: string): SpeciesEntry | undefined {
  return SPECIES.find((s) => s.id === id);
}

export const CATEGORY_LABEL: Record<SpeciesEntry["category"], string> = {
  reef: "🐠 Reef",
  turtle: "🐢 Turtles",
  shark: "🦈 Sharks",
  ray: "🐟 Rays",
  other: "✨ Other",
};
